### ISSUE TITLE
Failure when trying to install sharp

### ISSUE THREAD

**Issue by m-Just** [Kyle-Kyle/buy-buy#13]
The error message is shown as below,
> PS D:\Courses\CSCI3100\project\buy-buy\Backend> npm install sharp
> 
> > sharp@0.17.2 install D:\Courses\CSCI3100\project\buy-buy\Backend\node_modules\s
> > node-gyp rebuild
> 
> 
> D:\Courses\CSCI3100\project\buy-buy\Backend\node_modules\sharp>if not defined npm
> les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, p
> TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the f
> end\node_modules\sharp\build\libvips-cpp.vcxproj]
> 
> 
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` faile
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\n
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process
> gyp ERR! System Windows_NT 10.0.14393
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs
> p.js" "rebuild"
> gyp ERR! cwd D:\Courses\CSCI3100\project\buy-buy\Backend\node_modules\sharp
> gyp ERR! node -v v6.10.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\n
> npm ERR! node v6.10.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! sharp@0.17.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sharp@0.17.2 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the sharp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs sharp
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls sharp
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\Courses\CSCI3100\project\buy-buy\Backend\npm-debug.log

**Comment by Kyle-Kyle** [comment]
Lack of come C++ package for `npm`. Try to create a Visual C++ project in Visual Studio to install required package.
